//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int ID { get; set; }
        public string Descriptions { get; set; }
        public string Image2 { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public string Desciption1 { get; set; }
        public string SmallImage { get; set; }
        public string LargeImage { get; set; }
        public string Heading2 { get; set; }
        public string PageHeading { get; set; }
        public string Description2 { get; set; }
        public string Image1 { get; set; }
        public string Heading3 { get; set; }
        public string Description3 { get; set; }
    }
}
