//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUs2
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Pro_time { get; set; }
        public string Pro_budget { get; set; }
        public string Message { get; set; }
        public string Company_name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public string File_name { get; set; }
        public string SourceURL { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> InquiryStatusID { get; set; }
        public string Note { get; set; }
        public Nullable<int> quantity { get; set; }
        public string dumm { get; set; }
    
        public virtual InquiryStatus2 InquiryStatus2 { get; set; }
    }
}
