//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public short ID { get; set; }
        public string Title { get; set; }
        public string Decsription { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public string Image { get; set; }
    }
}
