//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryPhoto
    {
        public int ID { get; set; }
        public int GalleryID { get; set; }
        public string Image { get; set; }
    
        public virtual Gallery Gallery { get; set; }
    }
}
