//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobApplications = new HashSet<JobApplication>();
        }
    
        public int ID { get; set; }
        public string JobTitle { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public string NoOfPeople { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public Nullable<int> ApplicationSubmitted { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplication> JobApplications { get; set; }
    }
}
