//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int ID { get; set; }
        public Nullable<int> PolicyCategory { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
    
        public virtual PolicyCategory PolicyCategory1 { get; set; }
    }
}
