//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OtherImages = new HashSet<OtherImage>();
            this.tblProductColors = new HashSet<tblProductColor>();
            this.ProductCategories = new HashSet<ProductCategory>();
            this.ProductPhotos = new HashSet<ProductPhoto>();
            this.tblcarts = new HashSet<tblcart>();
        }
    
        public int ID { get; set; }
        public Nullable<short> CategoryID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string ProductName { get; set; }
        public string Model { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> Price { get; set; }
        public decimal Discount { get; set; }
        public string Description { get; set; }
        public string ProductCompany { get; set; }
        public string ProductFeatures { get; set; }
        public string ProductSpecification { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyWords { get; set; }
        public string MetaDescription { get; set; }
        public string ShortDescription { get; set; }
        public string ProductTags { get; set; }
        public Nullable<bool> IsExclusive { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> Discountfixed { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Url { get; set; }
        public string OtherPhotosText { get; set; }
        public Nullable<bool> IsStock { get; set; }
        public string isbn_number { get; set; }
        public Nullable<bool> Optionional { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string USPrice { get; set; }
        public string FactoryPhotosText { get; set; }
        public string CertificationPhotosText { get; set; }
        public string ExhibitionPhotosText { get; set; }
        public string OEMODMServicePhotosText { get; set; }
        public Nullable<int> SizeID { get; set; }
        public string PdfFileName { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public bool ShowHome { get; set; }
        public string VideoEmbed { get; set; }
        public Nullable<int> SmallLength { get; set; }
        public string SmallPairOfShoes { get; set; }
        public Nullable<decimal> SmallPrice { get; set; }
        public Nullable<int> MediumLength { get; set; }
        public string MediumPairOfShoes { get; set; }
        public Nullable<decimal> MediumPrice { get; set; }
        public Nullable<int> LargeLength { get; set; }
        public string LargePairOfShoes { get; set; }
        public Nullable<decimal> LargePrice { get; set; }
        public Nullable<int> SmallWidth { get; set; }
        public Nullable<int> SmallHeight { get; set; }
        public Nullable<int> MediumWidth { get; set; }
        public Nullable<int> MediumHeight { get; set; }
        public Nullable<int> LargeWidth { get; set; }
        public Nullable<int> LargeHeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherImage> OtherImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductColor> tblProductColors { get; set; }
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ProductCategory1 ProductCategory { get; set; }
        public virtual ProductSize ProductSize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPhoto> ProductPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcart> tblcarts { get; set; }
    }
}
