//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public short ID { get; set; }
        public string Title { get; set; }
        public string Value { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Timing { get; set; }
        public string HomePageContent { get; set; }
        public string HomePageMetatTitle { get; set; }
        public string HomePageMetatKeyword { get; set; }
        public string HomePageMetatDescription { get; set; }
        public string WebFavicon { get; set; }
        public string WebLogo { get; set; }
        public string FooterLogo { get; set; }
        public string Client { get; set; }
    }
}
