//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingProductDetail
    {
        public int ID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductPrice { get; set; }
        public string Productquantity { get; set; }
        public string ProductVariation { get; set; }
        public string SKUCode { get; set; }
        public long ShippingOrderID { get; set; }
    
        public virtual OrderShippingDetail OrderShippingDetail { get; set; }
    }
}
