//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetting
    {
        public int ID { get; set; }
        public string SenderEmail { get; set; }
        public string SenderPassword { get; set; }
        public string SMTPHost { get; set; }
        public string Port { get; set; }
        public bool IsSSL { get; set; }
        public string Email { get; set; }
        public string FTPIP { get; set; }
        public string FtpName { get; set; }
        public string FtpPassword { get; set; }
        public string FTPPath { get; set; }
        public string SystemImage { get; set; }
    }
}
