//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcart()
        {
            this.OrderCarts = new HashSet<OrderCart>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }
        public int Discount { get; set; }
        public decimal DiscountPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public int Quantity { get; set; }
        public int status { get; set; }
        public string IPAdress { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string SuggestedColor { get; set; }
        public string SuggestedName { get; set; }
        public string SuggestedLogo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCart> OrderCarts { get; set; }
        public virtual Product Product { get; set; }
    }
}
