//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPage
    {
        public long ID { get; set; }
        public string Article_Content { get; set; }
        public string Title { get; set; }
        public string Meta_Keywords { get; set; }
        public string Meta_Description { get; set; }
        public string Meta_Title { get; set; }
        public int Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string SEO_URL { get; set; }
        public string Thumbnail { get; set; }
        public string short_description { get; set; }
        public Nullable<int> Member_id { get; set; }
        public string related_link { get; set; }
        public string content2 { get; set; }
        public string content3 { get; set; }
        public string content4 { get; set; }
        public Nullable<int> panel_id { get; set; }
        public Nullable<int> qualification_id { get; set; }
        public Nullable<int> insitute_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> Subj_id { get; set; }
        public Nullable<int> year_id { get; set; }
        public Nullable<int> pastpaper_id { get; set; }
    }
}
