//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeamMember
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Designation { get; set; }
        public string FacbookLink { get; set; }
        public string pinterest { get; set; }
        public string TwitterLink { get; set; }
        public string InstagramLink { get; set; }
        public string ShortDescription { get; set; }
        public string ImageName { get; set; }
    }
}
