//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVideo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string VideoUrl { get; set; }
        public string EmbededCode { get; set; }
        public string Image { get; set; }
        public string Url { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDesc { get; set; }
        public string MetaKeyword { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> IsTop { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AltTag { get; set; }
    }
}
