//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnologyProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechnologyProfile()
        {
            this.ProfileImages = new HashSet<ProfileImage>();
            this.ProfileVideos = new HashSet<ProfileVideo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string EntityName { get; set; }
        public string Qualification { get; set; }
        public string AffiliationName { get; set; }
        public string Nationality { get; set; }
        public string Nationality2 { get; set; }
        public string Nationality3 { get; set; }
        public string ContactDetails { get; set; }
        public string ContactDetailsOfTechnicalResources { get; set; }
        public string TechnologyName { get; set; }
        public string Synopsis { get; set; }
        public bool PrototypeAvailable { get; set; }
        public string Purpose_of_Technology { get; set; }
        public string TechnologyTargets { get; set; }
        public string DevelopedYear { get; set; }
        public string ApprovalsRequired { get; set; }
        public string OtherApprovalsRequired { get; set; }
        public string PotentialBenefiaciaries { get; set; }
        public string EndUserOfTechnology { get; set; }
        public string BenefitsOfTechnology { get; set; }
        public bool BenefitsOfTechnology2 { get; set; }
        public string ReserchCentreToDevelopTechnology { get; set; }
        public string FacilityAvailability { get; set; }
        public string RawMaterialAvailability { get; set; }
        public string ResourcesToEnablePilotPro { get; set; }
        public string ProductionCapacity { get; set; }
        public string ProductionCost { get; set; }
        public string OneUnitCost { get; set; }
        public bool TechnologySold { get; set; }
        public string SalePrice { get; set; }
        public string competingProductsSalesMarketing { get; set; }
        public string UniqueSellingPointSalesMarketing { get; set; }
        public string HowGreen { get; set; }
        public string SustainableProducts { get; set; }
        public string CompetingProductsSustainability { get; set; }
        public string UniqueSellingPointSustainability { get; set; }
        public string PerceivedImpactOnLocalEconomy { get; set; }
        public string PerceivedImpactOnServiceDelivery { get; set; }
        public string PerceivedImpactOnEmploymentGeneration { get; set; }
        public string PerceivedImpactOnEnvironment { get; set; }
        public string Society { get; set; }
        public string AttachAnnexures { get; set; }
        public string EstamatedImpact { get; set; }
        public string Supportexpectation { get; set; }
        public bool IsShow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileImage> ProfileImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileVideo> ProfileVideos { get; set; }
    }
}
