//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silkways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLBasedCMSPage
    {
        public int ID { get; set; }
        public string PageName { get; set; }
        public string Heading { get; set; }
        public string Pageimage { get; set; }
        public string URL { get; set; }
        public string Description { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int UserID { get; set; }
        public string IsGuide { get; set; }
    
        public virtual User User { get; set; }
    }
}
